language: bash
services: docker

install:
  - ls
  # - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - test='/';

script:
  - ls -l
  # - travis_retry docker build -t "$image" .

after_script:
  - docker images

# vim:set et ts=2 sw=2:
