language: bash
services: docker

env:
  - DOCKER_REPO=webdevops-wordpress

# install:
#   - ls
  # - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - TOKEN=$( curl -sSLd "username=${DOCKER_HUB_USERNAME}&password=${DOCKER_HUB_PASSWORD}" https://hub.docker.com/v2/users/login | jq -r '.token' )
  - NEW_TAG=$( curl -fsSL 'http://api.wordpress.org/core/version-check/1.7/' | jq -r '.offers[0].current' )
  - SHA1=$( curl -fsSL "https://wordpress.org/wordpress-${NEW_TAG}.tar.gz.sha1" )
  - "CURRENT_TAG=$( curl -sH \"Authorization: JWT ${TOKEN}\" \"https://hub.docker.com/v2/repositories/${DOCKER_HUB_USERNAME}/${DOCKER_REPO}/tags/${NEW_TAG}/\" | jq -r '.name' )"
  - echo "new tag: ${NEW_TAG}, current tag: ${CURRENT_TAG}"

script:
  - if [ $NEW_TAG = $CURRENT_TAG ]; then
      echo "Nothing new to build";
    else
      echo "Login to dockerhub";
      docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD};
      echo "Start building new image";
      cd ${DOCKER_REPO};
      travis_retry docker build --build-arg WORDPRESS_VERSION="${NEW_TAG}" --build-arg WORDPRESS_SHA1="${SHA1}" -t "${DOCKER_REPO}" . ;
      echo "Push new image with tags";
      docker tag ${DOCKER_REPO} "${DOCKER_HUB_USERNAME}/${DOCKER_REPO}:latest";
      docker push "${DOCKER_HUB_USERNAME}/${DOCKER_REPO}:latest";
      docker tag "${DOCKER_HUB_USERNAME}/${DOCKER_REPO}:latest" "${DOCKER_HUB_USERNAME}/${DOCKER_REPO}:${NEW_TAG}";
      docker push "${DOCKER_HUB_USERNAME}/${DOCKER_REPO}:${NEW_TAG}";
    fi
  # - travis_retry docker build -t "$image" .

after_script:
  - docker images

# vim:set et ts=2 sw=2:
